---
title: "google trends with R"
author: "Dusan Milosevic"
date: "December 27, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install.packages("gtrendsR")

library(gtrendsR)
library(dplyr)
library(lubridate)
library(ggplot2)
library(maps)
library(stringr)
```

## Google Trends 
```{r}
## UK query
allEventsUK <- gtrends(keyword = c("Christmas", "Thanksgiving", "Halloween", "Black Friday"),
                       time = "2017-01-01 2017-12-31",
                       geo = "GB")

allEventsUK <- allEventsUK$interest_over_time %>%
               mutate(hits = as.numeric(ifelse(hits == "<1", 0, hits)))

## US query 
allEventsUS <- gtrends(keyword = c("Christmas", "Thanksgiving",
                                   "Halloween", "Black Friday"),
                                    time = "2017-01-01 2017-12-31",
                                    geo = "US")

allEventsUS <- allEventsUS$interest_over_time %>%
               mutate(hits = as.numeric(ifelse(hits == "<1", 0, hits)))

# Combine UK and US data
allEvents <- rbind(allEventsUK, allEventsUS)

# Plot
plot <- allEvents %>% 
  ggplot(aes(date, hits, colour = keyword)) + 
  geom_line(size = 1) +
  facet_wrap(~ geo) +
  scale_x_datetime(limits = c(as.POSIXct("2017-07-01"), NA)) +
  theme_minimal()

plot
```

## Black Friday in each U.S. State in 2018
```{r}
bf <- gtrends(c("bf"), 
               gprop = "web", 
               time = "all", 
               geo = c("US"))

bfInterestByRegion <- as_tibble(bf$interest_by_region)

statesMap = map_data("state")

bfInterestByRegion <- bfInterestByRegion %>% 
  mutate(region = str_to_lower(location))

bfMerged <- bfInterestByRegion %>% 
  left_join(., statesMap, by = "region")

bfMerged %>% 
  glimpse(78)

bfRegionLabels <- bfMerged %>% 
  select(region, long, lat) %>% 
  group_by(region) %>% 
  filter(!is.na(lat) | !is.na(long)) %>% 
  summarise(lat = mean(range(lat)),
                   long = mean(range(long))) %>% 
  arrange(region)

bfRegionLabels %>% 
  head()

bfMerged %>% 
  ggplot(aes(x = long, y = lat)) +
  geom_polygon(aes(group = group, 
                            fill = log(hits))) +
  coord_fixed(1.3) +
  scale_fill_distiller(palette = "Reds") +
  ggtitle("Google search interest for bf in each state") +
  theme_classic()

```



